baseurl: /


# url: 
title: python -c "import this"
subtitle:  
author: zhwei
simple_search: http://google.com/search
description: zhwei@Notes:~$
email: sdutzhangwei@gmail.com

default_asides: [custom/asides/aboutme.html, asides/recent_posts.html, asides/github.html, asides/twitter.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]


# Facebook

facebook_user: zhweis

# Github repositories
github_user: zhwei
github_repo_count: 4
github_show_profile_link: true
github_skip_forks: false

# Disqus Comments
disqus_short_name: zhwei
disqus_show_comment_count: false


