################################
#                              #
# config file                  #
#                              #
################################

url: zhangweide.cn
baseurl: /
title: Zhwei's Blog
subtitle:
author: zhwei
simple_search: http://google.com/search
description: Be Your Personal Best
email: sdutzhangwei@gmail.com

category_dir: blog/categories
tags_path : /tags.html
markdown: kramdown


# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml



# 单篇文章的链接
#
permalink: /archive/:year/:title.html


# Third Party
#
weibo_user: 123271314
github_user: zhwei
twitter_user: zhweifcx
duoshuo: zhweigithub

