################################
#                              #
# config file                  #
#                              #
################################




url: zhangweide.cn
baseurl: /
title: zhwei@Notes:~$
subtitle:  
author: zhwei
simple_search: http://google.com/search
description: python -c 'import this'
email: sdutzhangwei@gmail.com

# 首页分页
#
paginate: 7           # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Continue &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
plugins: _plugins
markdown: rdiscount

category_dir: blog/categories
tags_path : /tags.html
markdown: rdiscount
pygments: false # default python pygments have been replaced by pygments.rb




# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml



# 单篇文章的链接
#
permalink: /archive/:year/:title.html


# 第三方工具  
#
# weibo 
weibo_user: 123271314

# Github repositories
github_user: zhwei
github_repo_count: 4
github_show_profile_link: true
github_skip_forks: false


# Facebook
facebook_user: zhweis

# Disqus Comments
disqus_short_name: importthis-zhwei
disqus_show_comment_count: false

