################################
#                              #
# config file                  #
#                              #
################################

url: zhangweide.cn
baseurl: /
title: Zhwei's Blog
author: zhwei
description: Be Your Personal Best

markdown: kramdown

tags_path : /tags.html
subscribe_rss: /atom.xml

# 单篇文章的链接
#
permalink: /archive/:year/:title.html
