baseurl: https://zhw.in
languageCode: zh-cn
theme: hugo-theme-stack
paginate: 10
title: zhwei's Blog

# Change it to your Disqus shortname before using
disqusShortname: zhwei

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn
DefaultContentLanguage: en

permalinks:
    post: /post/:slug
    page: /:slug

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: /images/favicon.ico

    footer:
        since: 2012
        customText:

    dateFormat:
        published: 2006-01-02
        lastUpdated: 2006-01-02 15:04 CST

    sidebar:
        emoji: 🏠
        subtitle: Be Your Personal Best
        avatar:
            local: true
            src: img/avatar.png

    article:
        math: false
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: disqus
        utterances:
            repo:
            issueTerm: pathname
            label:
            theme: preferred-color-scheme

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 10

        tagCloud:
            limit: 100

    opengraph:
        twitter:
            # Your Twitter username
            site: zhwei_

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          pre: home

        - identifier: about
          name: About
          url: about
          weight: -90
          pre: user

        - identifier: archives
          name: Archives
          url: archives
          weight: -70
          pre: archives

        - identifier: search
          name: Search
          url: search
          weight: -60
          pre: search

        - identifier: github
          name: GitHub
          url: https://github.com/zhwei
          weight: -50
          pre: brand-github

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    highlight:
        noClasses: false

googleAnalytics: "G-1JJRZSH9W8"